In [4]:
import pandas as pd
import sqlite3

In [2]:
sam = pd.read_csv('data/data_dictionary.csv')

In [3]:
sam.head()

,Category,Column Header,Business Header,Definition,Example,Unnamed: 5,Unnamed: 6
0,Electric Vehicles,VIN (1-10),VIN,Vehicle Identification Number,5YJ3E1EB6K,NaN,NaN
1,Electric Vehicles,County,County,The county in Washington state where the vehic...,King,NaN,NaN
2,Electric Vehicles,City,City,The city where the vehicle is registered.,Seattle,NaN,NaN
3,Electric Vehicles,State,State,The state where the vehicle is registered.,WA,NaN,NaN
4,Electric Vehicles,Postal Code,Postal Code,The postal code of the vehicle's registered lo...,98178,NaN,NaN

In [5]:
df = pd.read_csv('data/Electric_Vehicle_Population_Data.csv')


county_frequency = df['County'].value_counts()



top_7_counties = county_frequency.index[:7]

# Create a dictionary to store dataframes for each county
county_tables = {county: df[df['County'] == county] for county in top_7_counties}

# Connect to SQLite database (or create one if it doesn't exist)
conn = sqlite3.connect('data/electric_vehicle_data.db')

# Iterate through the county_tables dictionary and create tables
for county, table in county_tables.items():
    table.to_sql(county, conn, if_exists='replace', index=False)

# Close the connection
conn.close()

In [8]:
df[df['County']=='King'].head(5)

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,5YJ3E1EB6K,King,Seattle,WA,98178.0,2019,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,220.0,0.0,37.0,101250425,POINT (-122.23825 47.49461),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
3,5YJ3E1EBXN,King,Bellevue,WA,98004.0,2022,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,0.0,41.0,219428079,POINT (-122.1872 47.61001),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303302e+10
6,5YJ3E1EB6J,King,Burien,WA,98166.0,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215.0,0.0,34.0,278247826,POINT (-122.34134 47.46593),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303303e+10
8,KM8K23AGXL,King,Seattle,WA,98125.0,2020,HYUNDAI,KONA,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,258.0,0.0,46.0,145686754,POINT (-122.30253 47.72656),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10
9,1N4AZ0CP2F,King,Bellevue,WA,98006.0,2015,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,84.0,0.0,41.0,268997830,POINT (-122.12096 47.55584),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303302e+10

In [9]:
df[df['County']=='King'].head(5).to_csv('data/table.csv', index=False)